version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "form-builder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14r4ei11v9y21"
s3_prefix = "form-builder"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
