AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Form Builder application backend

Globals:
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Timeout: 15
    Environment:
      Variables:
        # Replace <username>, <password> and <clusterName> with the real values before the deployment or local testing
        mongoUrl: mongodb+srv://<username>:<password>@<clusterName>.mongodb.net/?retryWrites=true&w=majority&srvMaxHosts=3
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET,PUT,PATCH'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  FormBuilderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  RegisterFunction:
    Type: AWS::Serverless::Function
    CodeUri: functions/register
    Properties:
      FunctionName: FB-register
      Events:
        RegisterUser:
          Type: Api
          Properties:
            RestApiId: !Ref FormBuilderApi
            Path: /users/register
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/register/app.ts

  FormCreateFunction:
    Type: AWS::Serverless::Function
    CodeUri: functions/formCreate
    Properties:
      FunctionName: FB-formCreate
      Events:
        CreateForm:
          Type: Api
          Properties:
            RestApiId: !Ref FormBuilderApi
            Path: /forms
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/formCreate/app.ts

  FormListFunction:
    Type: AWS::Serverless::Function
    CodeUri: functions/formList
    Properties:
      FunctionName: FB-formList
      Events:
        CreateForm:
          Type: Api
          Properties:
            RestApiId: !Ref FormBuilderApi
            Path: /forms
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/formList/app.ts

Outputs:
  FormBuilderApi:
    Description: API Gateway endpoint URL for Prod stage of Form Builder app
    Value: !Sub "https://${FormBuilderApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
